package RestaurantLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Role extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Role() {
    super(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c61L, "Role", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263841");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CHEF_0 = new EnumerationDescriptor.MemberDescriptor("CHEF", "CHEF", 0x20a07844fbe96259L, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884441");
  private final EnumerationDescriptor.MemberDescriptor myMember_SOUS_CHEF_0 = new EnumerationDescriptor.MemberDescriptor("SOUS_CHEF", "SOUS_CHEF", 0x20a07844fbe9625bL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884443");
  private final EnumerationDescriptor.MemberDescriptor myMember_WAITER_0 = new EnumerationDescriptor.MemberDescriptor("WAITER", "WAITER", 0x20a07844fbe9625cL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884444");
  private final EnumerationDescriptor.MemberDescriptor myMember_CASHIER_0 = new EnumerationDescriptor.MemberDescriptor("CASHIER", "CASHIER", 0x20a07844fbe9625dL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884445");
  private final EnumerationDescriptor.MemberDescriptor myMember_HEAD_WAITER_0 = new EnumerationDescriptor.MemberDescriptor("HEAD_WAITER", "HEAD_WAITER", 0x20a07844fbe9625eL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884446");
  private final EnumerationDescriptor.MemberDescriptor myMember_HEAD_CHEF_0 = new EnumerationDescriptor.MemberDescriptor("HEAD_CHEF", "HEAD_CHEF", 0x20a07844fbe9625fL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884447");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c61L, 0x20a07844fbe96259L, 0x20a07844fbe9625bL, 0x20a07844fbe9625cL, 0x20a07844fbe9625dL, 0x20a07844fbe9625eL, 0x20a07844fbe9625fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CHEF_0, myMember_SOUS_CHEF_0, myMember_WAITER_0, myMember_CASHIER_0, myMember_HEAD_WAITER_0, myMember_HEAD_CHEF_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_WAITER_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CHEF":
        return myMember_CHEF_0;
      case "SOUS_CHEF":
        return myMember_SOUS_CHEF_0;
      case "WAITER":
        return myMember_WAITER_0;
      case "CASHIER":
        return myMember_CASHIER_0;
      case "HEAD_WAITER":
        return myMember_HEAD_WAITER_0;
      case "HEAD_CHEF":
        return myMember_HEAD_CHEF_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
