package RestaurantLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CourseType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CourseType() {
    super(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c49L, "CourseType", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263817");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_FRIED_0 = new EnumerationDescriptor.MemberDescriptor("FRIED", "FRIED", 0x20a07844fbef2c4bL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263819");
  private final EnumerationDescriptor.MemberDescriptor myMember_PIZZA_0 = new EnumerationDescriptor.MemberDescriptor("PIZZA", "PIZZA", 0x20a07844fbef2c4aL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263818");
  private final EnumerationDescriptor.MemberDescriptor myMember_MAIN_DISH_0 = new EnumerationDescriptor.MemberDescriptor("MAIN_DISH", "MAIN_DISH", 0x20a07844fbef2c4cL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263820");
  private final EnumerationDescriptor.MemberDescriptor myMember_NIGIRI_0 = new EnumerationDescriptor.MemberDescriptor("NIGIRI", "NIGIRI", 0x20a07844fbef2c4dL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263821");
  private final EnumerationDescriptor.MemberDescriptor myMember_DESSERT_0 = new EnumerationDescriptor.MemberDescriptor("DESSERT", "DESSERT", 0x20a07844fbef2c4eL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263822");
  private final EnumerationDescriptor.MemberDescriptor myMember_APPETIZER_0 = new EnumerationDescriptor.MemberDescriptor("APPETIZER", "APPETIZER", 0x20a07844fbef2c4fL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263823");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c49L, 0x20a07844fbef2c4bL, 0x20a07844fbef2c4aL, 0x20a07844fbef2c4cL, 0x20a07844fbef2c4dL, 0x20a07844fbef2c4eL, 0x20a07844fbef2c4fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_FRIED_0, myMember_PIZZA_0, myMember_MAIN_DISH_0, myMember_NIGIRI_0, myMember_DESSERT_0, myMember_APPETIZER_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_MAIN_DISH_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "FRIED":
        return myMember_FRIED_0;
      case "PIZZA":
        return myMember_PIZZA_0;
      case "MAIN_DISH":
        return myMember_MAIN_DISH_0;
      case "NIGIRI":
        return myMember_NIGIRI_0;
      case "DESSERT":
        return myMember_DESSERT_0;
      case "APPETIZER":
        return myMember_APPETIZER_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
