package RestaurantLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Gender extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Gender() {
    super(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c57L, "Gender", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263831");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_MALE_0 = new EnumerationDescriptor.MemberDescriptor("MALE", "MALE", 0x20a07844fbef2c58L, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263832");
  private final EnumerationDescriptor.MemberDescriptor myMember_FEMALE_0 = new EnumerationDescriptor.MemberDescriptor("FEMALE", "FEMALE", 0x20a07844fbef2c59L, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263833");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c57L, 0x20a07844fbef2c58L, 0x20a07844fbef2c59L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_MALE_0, myMember_FEMALE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_MALE_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "MALE":
        return myMember_MALE_0;
      case "FEMALE":
        return myMember_FEMALE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
