package RestaurantLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Material extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Material() {
    super(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c67L, "Material", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263847");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_WOOD_0 = new EnumerationDescriptor.MemberDescriptor("WOOD", "WOOD", 0x20a07844fbe96268L, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884456");
  private final EnumerationDescriptor.MemberDescriptor myMember_PLASTIC_0 = new EnumerationDescriptor.MemberDescriptor("PLASTIC", "PLASTIC", 0x20a07844fbe9626aL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884458");
  private final EnumerationDescriptor.MemberDescriptor myMember_GLASS_0 = new EnumerationDescriptor.MemberDescriptor("GLASS", "GLASS", 0x20a07844fbe9626bL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884459");
  private final EnumerationDescriptor.MemberDescriptor myMember_PLEXIGLASS_0 = new EnumerationDescriptor.MemberDescriptor("PLEXIGLASS", "PLEXIGLASS", 0x20a07844fbe9626cL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884460");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALUMINIUM_0 = new EnumerationDescriptor.MemberDescriptor("ALUMINIUM", "ALUMINIUM", 0x20a07844fbe9626dL, "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243166884461");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c67L, 0x20a07844fbe96268L, 0x20a07844fbe9626aL, 0x20a07844fbe9626bL, 0x20a07844fbe9626cL, 0x20a07844fbe9626dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_WOOD_0, myMember_PLASTIC_0, myMember_GLASS_0, myMember_PLEXIGLASS_0, myMember_ALUMINIUM_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_WOOD_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "WOOD":
        return myMember_WOOD_0;
      case "PLASTIC":
        return myMember_PLASTIC_0;
      case "GLASS":
        return myMember_GLASS_0;
      case "PLEXIGLASS":
        return myMember_PLEXIGLASS_0;
      case "ALUMINIUM":
        return myMember_ALUMINIUM_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
