package RestaurantLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Bathroom = 0;
  public static final int City = 1;
  public static final int Course = 2;
  public static final int Diagram = 3;
  public static final int DiningRoom = 4;
  public static final int Employee = 5;
  public static final int EmployeeRelation = 6;
  public static final int IRestaurantRelation = 7;
  public static final int Kitchen = 8;
  public static final int Menu = 9;
  public static final int Owner = 10;
  public static final int OwnerRelation = 11;
  public static final int Person = 12;
  public static final int Region = 13;
  public static final int Restaurant = 14;
  public static final int RestaurantArea = 15;
  public static final int Table = 16;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL);
    builder.put(0x20a07844fbef2c39L, Bathroom);
    builder.put(0x20a07844fbef2c40L, City);
    builder.put(0x20a07844fbef2c44L, Course);
    builder.put(0x20a07844fbef3745L, Diagram);
    builder.put(0x20a07844fbef2c7dL, DiningRoom);
    builder.put(0x20a07844fbef2c5bL, Employee);
    builder.put(0x78cc41cd11396c18L, EmployeeRelation);
    builder.put(0x529faf485a6b8e78L, IRestaurantRelation);
    builder.put(0x20a07844fbef2c7aL, Kitchen);
    builder.put(0x20a07844fbef2c77L, Menu);
    builder.put(0x20a07844fbef2c63L, Owner);
    builder.put(0x78cc41cd11396c16L, OwnerRelation);
    builder.put(0x20a07844fbef2c51L, Person);
    builder.put(0x20a07844fbef2c3eL, Region);
    builder.put(0x20a07844fbef429eL, Restaurant);
    builder.put(0x20a07844fbef2c6eL, RestaurantArea);
    builder.put(0x20a07844fbef2c73L, Table);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
