package RestaurantLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBathroom = createDescriptorForBathroom();
  /*package*/ final ConceptDescriptor myConceptCity = createDescriptorForCity();
  /*package*/ final ConceptDescriptor myConceptCourse = createDescriptorForCourse();
  /*package*/ final ConceptDescriptor myConceptDiagram = createDescriptorForDiagram();
  /*package*/ final ConceptDescriptor myConceptDiningRoom = createDescriptorForDiningRoom();
  /*package*/ final ConceptDescriptor myConceptEmployeRelation = createDescriptorForEmployeRelation();
  /*package*/ final ConceptDescriptor myConceptEmployee = createDescriptorForEmployee();
  /*package*/ final ConceptDescriptor myConceptKitchen = createDescriptorForKitchen();
  /*package*/ final ConceptDescriptor myConceptMenu = createDescriptorForMenu();
  /*package*/ final ConceptDescriptor myConceptOwner = createDescriptorForOwner();
  /*package*/ final ConceptDescriptor myConceptOwnerRelation = createDescriptorForOwnerRelation();
  /*package*/ final ConceptDescriptor myConceptPerson = createDescriptorForPerson();
  /*package*/ final ConceptDescriptor myConceptRegion = createDescriptorForRegion();
  /*package*/ final ConceptDescriptor myConceptRestaurant = createDescriptorForRestaurant();
  /*package*/ final ConceptDescriptor myConceptRestaurantArea = createDescriptorForRestaurantArea();
  /*package*/ final ConceptDescriptor myConceptTable = createDescriptorForTable();
  /*package*/ final EnumerationDescriptor myEnumerationCourseType = new EnumerationDescriptor_CourseType();
  /*package*/ final EnumerationDescriptor myEnumerationGender = new EnumerationDescriptor_Gender();
  /*package*/ final EnumerationDescriptor myEnumerationMaterial = new EnumerationDescriptor_Material();
  /*package*/ final EnumerationDescriptor myEnumerationRole = new EnumerationDescriptor_Role();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeDate = new ConstrainedStringDatatypeDescriptorImpl(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3aL, "Date", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263802", "[0-9]{2}/[0-9]{2}/[0-9]{4}");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeFiscalCode = new ConstrainedStringDatatypeDescriptorImpl(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x78cc41cd1138e4c3L, "FiscalCode", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/8704404528813368515", "[A-Z]{5,6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{2}[A-Z]");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeFloat = new ConstrainedStringDatatypeDescriptorImpl(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3cL, "Float", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263804", "[0-9]+.?[0-9]*");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeVatCode = new ConstrainedStringDatatypeDescriptorImpl(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3dL, "VatCode", "r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263805", "(IT)?[0-9]{11}");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBathroom, myConceptCity, myConceptCourse, myConceptDiagram, myConceptDiningRoom, myConceptEmployeRelation, myConceptEmployee, myConceptKitchen, myConceptMenu, myConceptOwner, myConceptOwnerRelation, myConceptPerson, myConceptRegion, myConceptRestaurant, myConceptRestaurantArea, myConceptTable);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Bathroom:
        return myConceptBathroom;
      case LanguageConceptSwitch.City:
        return myConceptCity;
      case LanguageConceptSwitch.Course:
        return myConceptCourse;
      case LanguageConceptSwitch.Diagram:
        return myConceptDiagram;
      case LanguageConceptSwitch.DiningRoom:
        return myConceptDiningRoom;
      case LanguageConceptSwitch.EmployeRelation:
        return myConceptEmployeRelation;
      case LanguageConceptSwitch.Employee:
        return myConceptEmployee;
      case LanguageConceptSwitch.Kitchen:
        return myConceptKitchen;
      case LanguageConceptSwitch.Menu:
        return myConceptMenu;
      case LanguageConceptSwitch.Owner:
        return myConceptOwner;
      case LanguageConceptSwitch.OwnerRelation:
        return myConceptOwnerRelation;
      case LanguageConceptSwitch.Person:
        return myConceptPerson;
      case LanguageConceptSwitch.Region:
        return myConceptRegion;
      case LanguageConceptSwitch.Restaurant:
        return myConceptRestaurant;
      case LanguageConceptSwitch.RestaurantArea:
        return myConceptRestaurantArea;
      case LanguageConceptSwitch.Table:
        return myConceptTable;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationCourseType, myEnumerationGender, myEnumerationMaterial, myEnumerationRole, myCSDatatypeDate, myCSDatatypeFiscalCode, myCSDatatypeFloat, myCSDatatypeVatCode);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBathroom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Bathroom", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c39L);
    b.class_(false, false, false);
    b.parent(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c6eL);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263801");
    b.version(3);
    b.property("numberOfToilets", 0x20a07844fbef2c81L).type(PrimitiveTypeId.INTEGER).origin("2351011243167263873").done();
    b.property("gender", 0x20a07844fbef2c82L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c57L)).origin("2351011243167263874").done();
    b.property("isAccessible", 0x20a07844fbef2c83L).type(PrimitiveTypeId.BOOLEAN).origin("2351011243167263875").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "City", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c40L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263808");
    b.version(3);
    b.property("cap", 0x20a07844fbef2c42L).type(PrimitiveTypeId.STRING).origin("2351011243167263810").done();
    b.associate("region", 0x20a07844fbef2c43L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3eL).optional(false).origin("2351011243167263811").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCourse() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Course", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c44L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263812");
    b.version(3);
    b.property("price", 0x20a07844fbef2c46L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3cL)).origin("2351011243167263814").done();
    b.property("type", 0x20a07844fbef2c47L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c49L)).origin("2351011243167263815").done();
    b.property("numberOfPieces", 0x20a07844fbef2c50L).type(PrimitiveTypeId.INTEGER).origin("2351011243167263824").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiagram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Diagram", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef3745L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167266629");
    b.version(3);
    b.aggregate("entities", 0x20a07844fbef3747L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL).optional(true).ordered(true).multiple(true).origin("2351011243167266631").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiningRoom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "DiningRoom", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c7dL);
    b.class_(false, false, false);
    b.parent(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c6eL);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263869");
    b.version(3);
    b.aggregate("tables", 0x20a07844fbef2c7fL).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c73L).optional(true).ordered(true).multiple(true).origin("2351011243167263871").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmployeRelation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "EmployeRelation", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x78cc41cd11396c18L);
    b.class_(false, false, false);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/8704404528813403160");
    b.version(3);
    b.associate("employe", 0x78cc41cd11396c19L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c5bL).optional(false).origin("8704404528813403161").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmployee() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Employee", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c5bL);
    b.class_(false, false, false);
    b.parent(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c51L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263835");
    b.version(3);
    b.property("contractExpirationDate", 0x20a07844fbef2c5dL).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3aL)).origin("2351011243167263837").done();
    b.property("contractSignDate", 0x20a07844fbef2c5eL).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3aL)).origin("2351011243167263838").done();
    b.property("salary", 0x20a07844fbef2c5fL).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3cL)).origin("2351011243167263839").done();
    b.property("role", 0x20a07844fbef2c60L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c61L)).origin("2351011243167263840").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKitchen() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Kitchen", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c7aL);
    b.class_(false, false, false);
    b.parent(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c6eL);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263866");
    b.version(3);
    b.property("numberOfStoves", 0x20a07844fbef2c7cL).type(PrimitiveTypeId.INTEGER).origin("2351011243167263868").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenu() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Menu", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c77L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263863");
    b.version(3);
    b.aggregate("courses", 0x20a07844fbef2c79L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c44L).optional(false).ordered(true).multiple(true).origin("2351011243167263865").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOwner() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Owner", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c63L);
    b.class_(false, false, false);
    b.parent(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c51L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263843");
    b.version(3);
    b.property("vat", 0x20a07844fbef2c65L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3dL)).origin("2351011243167263845").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOwnerRelation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "OwnerRelation", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x78cc41cd11396c16L);
    b.class_(false, false, false);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/8704404528813403158");
    b.version(3);
    b.associate("owner", 0x78cc41cd11396c17L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c63L).optional(false).origin("8704404528813403159").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPerson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Person", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c51L);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263825");
    b.version(3);
    b.property("surname", 0x20a07844fbef2c53L).type(PrimitiveTypeId.STRING).origin("2351011243167263827").done();
    b.property("fiscalCode", 0x20a07844fbef2c54L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x78cc41cd1138e4c3L)).origin("2351011243167263828").done();
    b.property("birthDate", 0x20a07844fbef2c55L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3aL)).origin("2351011243167263829").done();
    b.property("gender", 0x20a07844fbef2c56L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c57L)).origin("2351011243167263830").done();
    b.associate("birthPlace", 0x20a07844fbef2c5aL).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c40L).optional(false).origin("2351011243167263834").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRegion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Region", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263806");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRestaurant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Restaurant", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef429eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167269534");
    b.version(3);
    b.property("street", 0x20a07844fbef42a1L).type(PrimitiveTypeId.STRING).origin("2351011243167269537").done();
    b.property("telephone", 0x20a07844fbef42a2L).type(PrimitiveTypeId.STRING).origin("2351011243167269538").done();
    b.associate("city", 0x20a07844fbef42a4L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c40L).optional(false).origin("2351011243167269540").done();
    b.aggregate("rooms", 0x20a07844fbef42a5L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c6eL).optional(false).ordered(true).multiple(true).origin("2351011243167269541").done();
    b.aggregate("owners", 0x78cc41cd11396c1aL).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x78cc41cd11396c16L).optional(false).ordered(true).multiple(true).origin("8704404528813403162").done();
    b.aggregate("employes", 0x20a07844fbef42a9L).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x78cc41cd11396c18L).optional(true).ordered(true).multiple(true).origin("2351011243167269545").done();
    b.aggregate("menus", 0x20a07844fbef42aaL).target(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c77L).optional(false).ordered(true).multiple(true).origin("2351011243167269546").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRestaurantArea() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "RestaurantArea", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c6eL);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263854");
    b.version(3);
    b.property("perimeter", 0x20a07844fbef2c70L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3cL)).origin("2351011243167263856").done();
    b.property("area", 0x20a07844fbef2c71L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c3cL)).origin("2351011243167263857").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RestaurantLanguage", "Table", 0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c73L);
    b.class_(false, false, false);
    b.origin("r:ed2e1c8b-f3ce-4973-8d88-0d8c7147e936(RestaurantLanguage.structure)/2351011243167263859");
    b.version(3);
    b.property("number", 0x20a07844fbef2c74L).type(PrimitiveTypeId.INTEGER).origin("2351011243167263860").done();
    b.property("numberOfSeat", 0x20a07844fbef2c75L).type(PrimitiveTypeId.INTEGER).origin("2351011243167263861").done();
    b.property("material", 0x20a07844fbef2c76L).type(MetaIdFactory.dataTypeId(0xb104fc7d0eb94ddcL, 0x828f1118413b5a6bL, 0x20a07844fbef2c67L)).origin("2351011243167263862").done();
    return b.create();
  }
}
