package RestaurantLanguage.feedback;

/*Generated by MPS */

import jetbrains.mps.core.aspects.feedback.api.FeedbackAspect;
import org.jetbrains.annotations.NotNull;
import java.util.stream.Stream;
import jetbrains.mps.core.aspects.feedback.api.FeedbackPerConceptDescriptor;

public final class GeneratedFeedbackAspectFeedback implements FeedbackAspect {
  @NotNull
  @Override
  public Stream<FeedbackPerConceptDescriptor> getPerConceptDescriptors() {
    return Stream.of(new Owner_FeedbackFeedback(), new Employee_FeedbackFeedback(), new Restaurant_FeedbackFeedback());
  }
}
